/**
 * JSON Schema format adapter — generator.
 *
 * Generates JSON Schema (draft-07 compatible) from a SchemaDocument.
 * Produces deterministic output via sorted keys and consistent formatting.
 *
 * @module
 */

import type { SchemaDocument, SchemaNode, GenerateOptions, ObjectSchema } from '../../core/types';

const HEADER_COMMENT = 'Generated by typeshift — do not edit manually.';

/**
 * Generate JSON Schema text from a SchemaDocument.
 *
 * If the document contains a single definition, it is emitted as the root schema.
 * If multiple definitions exist, they are placed under `$defs` with the first
 * definition as the root `$ref`.
 */
export function generateJsonSchema(document: SchemaDocument, options?: GenerateOptions): string {
  const entries = Object.entries(document.definitions);

  if (entries.length === 0) {
    return JSON.stringify({ $schema: 'http://json-schema.org/draft-07/schema#' }, null, 2) + '\n';
  }

  let schema: Record<string, unknown>;

  if (entries.length === 1) {
    const [name, node] = entries[0];
    schema = {
      $schema: 'http://json-schema.org/draft-07/schema#',
      ...(options?.header !== false ? { $comment: HEADER_COMMENT } : {}),
      title: name,
      ...nodeToSchema(node),
    };
  } else {
    // Multiple definitions → use $defs + root $ref
    const defs: Record<string, unknown> = {};
    for (const [name, node] of entries) {
      defs[name] = nodeToSchema(node);
    }

    schema = {
      $schema: 'http://json-schema.org/draft-07/schema#',
      ...(options?.header !== false ? { $comment: HEADER_COMMENT } : {}),
      $ref: `#/$defs/${entries[0][0]}`,
      $defs: defs,
    };
  }

  return JSON.stringify(schema, null, 2) + '\n';
}

// ── Schema node conversion ───────────────────────────────────────

function nodeToSchema(node: SchemaNode): Record<string, unknown> {
  let schema = nodeToBaseSchema(node);

  // Handle nullable
  if (node.nullable) {
    const currentType = schema.type;
    if (typeof currentType === 'string') {
      schema = { ...schema, type: [currentType, 'null'] };
    } else if (!currentType) {
      // For complex types (union, etc.), wrap with oneOf + null
      schema = { oneOf: [schema, { type: 'null' }] };
    }
  }

  // Metadata
  if (node.description) {
    schema = { ...schema, description: node.description };
  }
  if (node.default !== undefined) {
    schema = { ...schema, default: node.default };
  }

  return schema;
}

function nodeToBaseSchema(node: SchemaNode): Record<string, unknown> {
  switch (node.kind) {
    case 'string': {
      const s: Record<string, unknown> = { type: 'string' };
      if (node.minLength !== undefined) s.minLength = node.minLength;
      if (node.maxLength !== undefined) s.maxLength = node.maxLength;
      if (node.pattern !== undefined) s.pattern = node.pattern;
      if (node.format !== undefined) s.format = node.format;
      return s;
    }

    case 'number':
      return numericSchema('number', node);

    case 'integer':
      return numericSchema('integer', node);

    case 'boolean':
      return { type: 'boolean' };

    case 'null':
      return { type: 'null' };

    case 'any':
      return {};

    case 'literal':
      return { const: node.value };

    case 'array':
      return arraySchema(node);

    case 'tuple':
      return {
        type: 'array',
        items: node.items.map((i) => nodeToSchema(i)),
        minItems: node.items.length,
        maxItems: node.items.length,
      };

    case 'object':
      return objectSchema(node);

    case 'record':
      return {
        type: 'object',
        additionalProperties: nodeToSchema(node.valueSchema),
      };

    case 'union':
      return { oneOf: node.schemas.map((s) => nodeToSchema(s)) };

    case 'intersection':
      return { allOf: node.schemas.map((s) => nodeToSchema(s)) };

    case 'enum':
      return { enum: [...node.values] };

    case 'ref':
      return { $ref: `#/$defs/${node.ref}` };
  }
}

function numericSchema(
  kind: 'number' | 'integer',
  node: {
    minimum?: number;
    maximum?: number;
    exclusiveMinimum?: number;
    exclusiveMaximum?: number;
    multipleOf?: number;
  },
): Record<string, unknown> {
  const s: Record<string, unknown> = { type: kind };
  if (node.minimum !== undefined) s.minimum = node.minimum;
  if (node.maximum !== undefined) s.maximum = node.maximum;
  if (node.exclusiveMinimum !== undefined) s.exclusiveMinimum = node.exclusiveMinimum;
  if (node.exclusiveMaximum !== undefined) s.exclusiveMaximum = node.exclusiveMaximum;
  if (node.multipleOf !== undefined) s.multipleOf = node.multipleOf;
  return s;
}

function arraySchema(node: {
  items: SchemaNode;
  minItems?: number;
  maxItems?: number;
  uniqueItems?: boolean;
}): Record<string, unknown> {
  const s: Record<string, unknown> = {
    type: 'array',
    items: nodeToSchema(node.items),
  };
  if (node.minItems !== undefined) s.minItems = node.minItems;
  if (node.maxItems !== undefined) s.maxItems = node.maxItems;
  if (node.uniqueItems) s.uniqueItems = true;
  return s;
}

function objectSchema(node: ObjectSchema): Record<string, unknown> {
  const s: Record<string, unknown> = { type: 'object' };
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  for (const [name, propDef] of Object.entries(node.properties)) {
    let propSchema = nodeToSchema(propDef.schema);
    if (propDef.description) {
      propSchema = { ...propSchema, description: propDef.description };
    }
    properties[name] = propSchema;
    if (!propDef.optional) {
      required.push(name);
    }
  }

  if (Object.keys(properties).length > 0) {
    s.properties = properties;
  }
  if (required.length > 0) {
    s.required = required;
  }
  if (node.additionalProperties === false) {
    s.additionalProperties = false;
  } else if (typeof node.additionalProperties === 'object') {
    s.additionalProperties = nodeToSchema(node.additionalProperties);
  }

  return s;
}
