// Generated by typeshift — do not edit manually.

import { z } from 'zod';

export const Product = z.object({
  sku: z.string().min(3).max(30),
  name: z.string().min(1),
  price: z.number().nonnegative(),
  stock: z.number().int().min(0),
  category: z.enum(["electronics", "apparel", "home", "books"]),
  websiteUrl: z.string().url().optional(),
}).describe("Inventory product with pricing and classification constraints");
