// Generated by typeshift — do not edit manually.

/** Pet category classification */
export interface Category {
  id: number;
  name: string;
}

export interface Tag {
  id: number;
  name: string;
}

/** Pet entity in the store */
export interface Pet {
  id: number;
  name: string;
  category?: Category;
  photoUrls: string[];
  tags?: Tag[];
  status?: "available" | "pending" | "sold";
}
