/**
 * TypeScript format adapter — generator.
 *
 * Generates TypeScript interface/type declarations from a SchemaDocument.
 * Produces deterministic output — same IR always produces the same output.
 *
 * @module
 */

import type {
  SchemaDocument,
  SchemaNode,
  ObjectSchema,
  PropertyDefinition,
} from '../../core/types';
import type { GenerateOptions } from '../../core/types';

const HEADER = '// Generated by typeshift — do not edit manually.\n';

/**
 * Generate TypeScript source text from a SchemaDocument.
 */
export function generateTypeScript(document: SchemaDocument, options?: GenerateOptions): string {
  const lines: string[] = [];

  if (options?.header !== false) {
    lines.push(HEADER);
  }

  const entries = Object.entries(document.definitions);
  for (let i = 0; i < entries.length; i++) {
    const [name, schema] = entries[i];

    // Emit description as JSDoc
    if (schema.description) {
      lines.push(formatJSDoc(schema.description));
    }

    if (schema.kind === 'object' && !schema.nullable) {
      lines.push(`export interface ${name} ${generateObjectBody(schema)}`);
    } else {
      lines.push(`export type ${name} = ${generateType(schema)};`);
    }

    if (i < entries.length - 1) {
      lines.push('');
    }
  }

  return lines.join('\n') + '\n';
}

// ── Type generation ──────────────────────────────────────────────

function generateType(node: SchemaNode): string {
  let base = generateBaseType(node);

  if (node.nullable) {
    base = `${wrapIfCompound(base, node)} | null`;
  }

  return base;
}

function generateBaseType(node: SchemaNode): string {
  switch (node.kind) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    case 'any':
      return 'unknown';

    case 'literal':
      if (typeof node.value === 'string') return JSON.stringify(node.value);
      return String(node.value);

    case 'array':
      return `${wrapIfCompound(generateType(node.items), node.items)}[]`;

    case 'tuple':
      return `[${node.items.map((i) => generateType(i)).join(', ')}]`;

    case 'object':
      return generateObjectBody(node);

    case 'record':
      return `Record<${generateType(node.keySchema)}, ${generateType(node.valueSchema)}>`;

    case 'union':
      return node.schemas.map((s) => generateType(s)).join(' | ');

    case 'intersection':
      return node.schemas.map((s) => wrapIfUnion(generateType(s), s)).join(' & ');

    case 'enum':
      return node.values
        .map((v) => (typeof v === 'string' ? JSON.stringify(v) : String(v)))
        .join(' | ');

    case 'ref':
      return node.ref;
  }
}

function generateObjectBody(node: ObjectSchema): string {
  const entries = Object.entries(node.properties);
  if (entries.length === 0) {
    return '{}';
  }

  const lines: string[] = ['{'];

  for (const [propName, propDef] of entries) {
    const propLines = generateProperty(propName, propDef);
    for (const line of propLines) {
      lines.push(`  ${line}`);
    }
  }

  lines.push('}');
  return lines.join('\n');
}

function generateProperty(name: string, prop: PropertyDefinition): string[] {
  const lines: string[] = [];

  // JSDoc for property description
  const desc = prop.description ?? prop.schema.description;
  if (desc) {
    lines.push(...formatJSDoc(desc).split('\n'));
  }

  const readonly = prop.readonly ? 'readonly ' : '';
  const optional = prop.optional ? '?' : '';
  const safeName = needsQuoting(name) ? JSON.stringify(name) : name;
  const type = generateType(prop.schema);

  lines.push(`${readonly}${safeName}${optional}: ${type};`);

  return lines;
}

// ── Formatting helpers ───────────────────────────────────────────

function formatJSDoc(description: string): string {
  const lines = description.split('\n');
  if (lines.length === 1) {
    return `/** ${description} */`;
  }
  return ['/**', ...lines.map((l) => ` * ${l}`), ' */'].join('\n');
}

/** Wrap type in parens if it's a compound type (union/intersection) used in array context. */
function wrapIfCompound(typeStr: string, node: SchemaNode): string {
  if (node.kind === 'union' || node.kind === 'intersection' || node.kind === 'enum') {
    return `(${typeStr})`;
  }
  if (node.nullable) {
    return `(${typeStr})`;
  }
  return typeStr;
}

/** Wrap type in parens if it's a union used in intersection context. */
function wrapIfUnion(typeStr: string, node: SchemaNode): string {
  if (node.kind === 'union' || node.kind === 'enum') {
    return `(${typeStr})`;
  }
  return typeStr;
}

/** Check if a property name needs quoting. */
function needsQuoting(name: string): boolean {
  return !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}
