/**
 * Zod format adapter — generator.
 *
 * Generates Zod schema source code from a SchemaDocument.
 * Produces deterministic output — same IR always produces the same code.
 *
 * @module
 */

import type { SchemaDocument, SchemaNode, GenerateOptions, ObjectSchema } from '../../core/types';

const HEADER = '// Generated by typeshift — do not edit manually.\n';

/**
 * Generate Zod schema source text from a SchemaDocument.
 */
export function generateZod(document: SchemaDocument, options?: GenerateOptions): string {
  const lines: string[] = [];

  if (options?.header !== false) {
    lines.push(HEADER);
  }

  lines.push("import { z } from 'zod';");
  lines.push('');

  const entries = Object.entries(document.definitions);
  for (let i = 0; i < entries.length; i++) {
    const [name, schema] = entries[i];
    const expr = generateExpression(schema);
    lines.push(`export const ${name} = ${expr};`);

    if (i < entries.length - 1) {
      lines.push('');
    }
  }

  return lines.join('\n') + '\n';
}

// ── Expression generation ────────────────────────────────────────

function generateExpression(node: SchemaNode): string {
  let expr = generateBaseExpression(node);

  // Apply common modifiers
  if (node.nullable) {
    expr += '.nullable()';
  }
  if (node.default !== undefined) {
    expr += `.default(${formatValue(node.default)})`;
  }
  if (node.description) {
    expr += `.describe(${JSON.stringify(node.description)})`;
  }

  return expr;
}

function generateBaseExpression(node: SchemaNode): string {
  switch (node.kind) {
    case 'string':
      return generateString(node);

    case 'number':
      return generateNumber(node);

    case 'integer':
      return generateInteger(node);

    case 'boolean':
      return 'z.boolean()';

    case 'null':
      return 'z.null()';

    case 'any':
      return 'z.any()';

    case 'literal':
      return `z.literal(${formatValue(node.value)})`;

    case 'array':
      return generateArray(node);

    case 'tuple':
      return `z.tuple([${node.items.map((i) => generateExpression(i)).join(', ')}])`;

    case 'object':
      return generateObject(node);

    case 'record':
      return `z.record(${generateExpression(node.keySchema)}, ${generateExpression(node.valueSchema)})`;

    case 'union':
      return `z.union([${node.schemas.map((s) => generateExpression(s)).join(', ')}])`;

    case 'intersection': {
      if (node.schemas.length < 2) {
        return node.schemas.length === 1 ? generateExpression(node.schemas[0]) : 'z.any()';
      }
      // Chain .and() calls: a.and(b).and(c)
      let expr = generateExpression(node.schemas[0]);
      for (let i = 1; i < node.schemas.length; i++) {
        expr += `.and(${generateExpression(node.schemas[i])})`;
      }
      return expr;
    }

    case 'enum':
      if (node.values.every((v) => typeof v === 'string')) {
        return `z.enum([${node.values.map((v) => JSON.stringify(v)).join(', ')}])`;
      }
      // Mixed enum → union of literals
      return `z.union([${node.values.map((v) => `z.literal(${formatValue(v)})`).join(', ')}])`;

    case 'ref':
      return node.ref;
  }
}

function generateString(node: {
  minLength?: number;
  maxLength?: number;
  pattern?: string;
  format?: string;
}): string {
  let expr = 'z.string()';

  // Format shortcuts
  if (node.format) {
    const formatMethod = FORMAT_MAP[node.format];
    if (formatMethod) {
      expr += `.${formatMethod}()`;
    }
  }

  if (node.minLength !== undefined) expr += `.min(${node.minLength})`;
  if (node.maxLength !== undefined) expr += `.max(${node.maxLength})`;
  if (node.pattern !== undefined) expr += `.regex(/${escapeRegex(node.pattern)}/)`;

  return expr;
}

function generateNumber(node: {
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number;
  exclusiveMaximum?: number;
  multipleOf?: number;
}): string {
  let expr = 'z.number()';

  if (node.exclusiveMinimum === 0) {
    expr += '.positive()';
  } else if (node.minimum === 0) {
    expr += '.nonnegative()';
  } else if (node.minimum !== undefined) {
    expr += `.min(${node.minimum})`;
  } else if (node.exclusiveMinimum !== undefined) {
    expr += `.min(${node.exclusiveMinimum + 1})`; // Approximate
  }

  if (node.exclusiveMaximum === 0) {
    expr += '.negative()';
  } else if (node.maximum === 0) {
    expr += '.nonpositive()';
  } else if (node.maximum !== undefined) {
    expr += `.max(${node.maximum})`;
  } else if (node.exclusiveMaximum !== undefined) {
    expr += `.max(${node.exclusiveMaximum - 1})`; // Approximate
  }

  if (node.multipleOf !== undefined) expr += `.multipleOf(${node.multipleOf})`;

  return expr;
}

function generateInteger(node: {
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number;
  exclusiveMaximum?: number;
  multipleOf?: number;
}): string {
  let expr = 'z.number().int()';

  if (node.minimum !== undefined) expr += `.min(${node.minimum})`;
  if (node.maximum !== undefined) expr += `.max(${node.maximum})`;
  if (node.multipleOf !== undefined) expr += `.multipleOf(${node.multipleOf})`;

  return expr;
}

function generateArray(node: {
  items: SchemaNode;
  minItems?: number;
  maxItems?: number;
  uniqueItems?: boolean;
}): string {
  let expr = `z.array(${generateExpression(node.items)})`;

  if (node.minItems !== undefined) expr += `.min(${node.minItems})`;
  if (node.maxItems !== undefined) expr += `.max(${node.maxItems})`;

  return expr;
}

function generateObject(node: ObjectSchema): string {
  const entries = Object.entries(node.properties);

  if (entries.length === 0) {
    return 'z.object({})';
  }

  const propLines: string[] = [];
  for (const [name, propDef] of entries) {
    const safeName = needsQuoting(name) ? JSON.stringify(name) : name;
    let expr = generateExpression(propDef.schema);

    if (propDef.optional) {
      expr += '.optional()';
    }

    // Add property description if different from schema description
    if (propDef.description && propDef.description !== propDef.schema.description) {
      expr += `.describe(${JSON.stringify(propDef.description)})`;
    }

    propLines.push(`  ${safeName}: ${expr},`);
  }

  return `z.object({\n${propLines.join('\n')}\n})`;
}

// ── Helpers ──────────────────────────────────────────────────────

const FORMAT_MAP: Record<string, string> = {
  email: 'email',
  uri: 'url',
  'date-time': 'datetime',
  uuid: 'uuid',
  ipv4: 'ip',
};

function formatValue(val: unknown): string {
  if (typeof val === 'string') return JSON.stringify(val);
  if (typeof val === 'number' || typeof val === 'boolean') return String(val);
  if (val === null) return 'null';
  return JSON.stringify(val);
}

function escapeRegex(pattern: string): string {
  // Escape forward slashes for use in /pattern/ literal
  return pattern.replace(/\//g, '\\/');
}

function needsQuoting(name: string): boolean {
  return !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}
