/**
 * OpenAPI 3.1 format adapter — generator.
 *
 * Generates valid OpenAPI 3.1.0 specifications with component schemas
 * in `components.schemas` from a SchemaDocument.
 * Produces deterministic output via sorted keys and consistent formatting.
 *
 * @module
 */

import type {
  SchemaDocument,
  SchemaNode,
  GenerateOptions,
  ObjectSchema,
} from '../../core/types';

const HEADER_NOTICE = 'Generated by typeshift — do not edit manually.';

/**
 * Generate an OpenAPI 3.1.0 JSON specification from a SchemaDocument.
 *
 * Emits all schemas in `components.schemas` and cross-references them
 * using `#/components/schemas/<Name>`.
 */
export function generateOpenApi(document: SchemaDocument, options?: GenerateOptions): string {
  const entries = Object.entries(document.definitions);

  // Deterministically sort component schemas by name
  entries.sort(([a], [b]) => a.localeCompare(b));

  const schemas: Record<string, unknown> = {};
  for (const [name, node] of entries) {
    schemas[name] = nodeToOpenApiSchema(node);
  }

  const doc: Record<string, unknown> = {
    openapi: '3.1.0',
    info: {
      title: document.metadata?.title ?? 'API Schemas',
      version: '1.0.0',
      ...(document.metadata?.description ? { description: document.metadata.description } : {}),
      ...(options?.header !== false ? { 'x-generated-by': HEADER_NOTICE } : {}),
    },
    paths: {},
    components: {
      schemas,
    },
  };

  return JSON.stringify(doc, null, 2) + '\n';
}

// ── Node conversion ───────────────────────────────────────────────

function nodeToOpenApiSchema(node: SchemaNode): Record<string, unknown> {
  let schema = nodeToBaseSchema(node);

  // Handle nullable (OpenAPI 3.1 uses JSON Schema 2020-12 type arrays)
  if (node.nullable) {
    const currentType = schema.type;
    if (typeof currentType === 'string') {
      schema = { ...schema, type: [currentType, 'null'] };
    } else if (!currentType) {
      schema = { oneOf: [schema, { type: 'null' }] };
    }
  }

  // Metadata
  if (node.description) {
    schema = { ...schema, description: node.description };
  }
  if (node.default !== undefined) {
    schema = { ...schema, default: node.default };
  }

  return schema;
}

function nodeToBaseSchema(node: SchemaNode): Record<string, unknown> {
  switch (node.kind) {
    case 'string': {
      const s: Record<string, unknown> = { type: 'string' };
      if (node.minLength !== undefined) s.minLength = node.minLength;
      if (node.maxLength !== undefined) s.maxLength = node.maxLength;
      if (node.pattern !== undefined) s.pattern = node.pattern;
      if (node.format !== undefined) s.format = node.format;
      return s;
    }

    case 'number':
      return numericSchema('number', node);

    case 'integer':
      return numericSchema('integer', node);

    case 'boolean':
      return { type: 'boolean' };

    case 'null':
      return { type: 'null' };

    case 'any':
      return {};

    case 'literal':
      return { const: node.value };

    case 'array':
      return arraySchema(node);

    case 'tuple':
      return {
        type: 'array',
        prefixItems: node.items.map((i) => nodeToOpenApiSchema(i)),
        minItems: node.items.length,
        maxItems: node.items.length,
      };

    case 'object':
      return objectSchema(node);

    case 'record':
      return {
        type: 'object',
        additionalProperties: nodeToOpenApiSchema(node.valueSchema),
      };

    case 'union':
      return { oneOf: node.schemas.map((s) => nodeToOpenApiSchema(s)) };

    case 'intersection':
      return { allOf: node.schemas.map((s) => nodeToOpenApiSchema(s)) };

    case 'enum':
      return { enum: [...node.values] };

    case 'ref':
      return { $ref: `#/components/schemas/${node.ref}` };
  }
}

function numericSchema(
  kind: 'number' | 'integer',
  node: {
    minimum?: number;
    maximum?: number;
    exclusiveMinimum?: number;
    exclusiveMaximum?: number;
    multipleOf?: number;
  },
): Record<string, unknown> {
  const s: Record<string, unknown> = { type: kind };
  if (node.minimum !== undefined) s.minimum = node.minimum;
  if (node.maximum !== undefined) s.maximum = node.maximum;
  if (node.exclusiveMinimum !== undefined) s.exclusiveMinimum = node.exclusiveMinimum;
  if (node.exclusiveMaximum !== undefined) s.exclusiveMaximum = node.exclusiveMaximum;
  if (node.multipleOf !== undefined) s.multipleOf = node.multipleOf;
  return s;
}

function arraySchema(node: {
  items: SchemaNode;
  minItems?: number;
  maxItems?: number;
  uniqueItems?: boolean;
}): Record<string, unknown> {
  const s: Record<string, unknown> = {
    type: 'array',
    items: nodeToOpenApiSchema(node.items),
  };
  if (node.minItems !== undefined) s.minItems = node.minItems;
  if (node.maxItems !== undefined) s.maxItems = node.maxItems;
  if (node.uniqueItems !== undefined) s.uniqueItems = node.uniqueItems;
  return s;
}

function objectSchema(node: ObjectSchema): Record<string, unknown> {
  const s: Record<string, unknown> = { type: 'object' };
  const properties: Record<string, unknown> = {};
  const required: string[] = [];

  // Sort properties deterministically
  const propEntries = Object.entries(node.properties).sort(([a], [b]) => a.localeCompare(b));

  for (const [name, propDef] of propEntries) {
    const propSchema = nodeToOpenApiSchema(propDef.schema);
    if (propDef.description) {
      propSchema.description = propDef.description;
    }
    if (propDef.readonly) {
      propSchema.readOnly = true;
    }
    properties[name] = propSchema;

    if (!propDef.optional) {
      required.push(name);
    }
  }

  s.properties = properties;

  if (required.length > 0) {
    s.required = required;
  }

  if (node.additionalProperties !== undefined) {
    if (typeof node.additionalProperties === 'boolean') {
      s.additionalProperties = node.additionalProperties;
    } else {
      s.additionalProperties = nodeToOpenApiSchema(node.additionalProperties);
    }
  }

  return s;
}
