// Generated by typeshift — do not edit manually.

/** User account registration contract */
export interface Account {
  accountNumber: string;
  email: string;
  age: number;
  password: string;
  isVerified?: boolean;
}
